language: rust
#sudo: false
sudo: required
dist: trusty

rust:
  - nightly
#  - beta
#  - stable

addons:
  apt:
    packages:
      - nasm

# before_install:
#   - wget http://security.ubuntu.com/ubuntu/pool/universe/liba/libav/libavutil52_9.18-0ubuntu0.14.04.1_amd64.deb
#   - sudo dpkg -i libavutil52_9.18-0ubuntu0.14.04.1_amd64.deb
#   - sudo apt-get -y install libavutil-dev libavformat-dev libavcodec-dev libswscale-dev libavdevice-dev libavfilter-dev
#   - wget http://security.ubuntu.com/ubuntu/pool/universe/liba/libav/libavresample1_9.18-0ubuntu0.14.04.1_amd64.deb
#   - wget http://security.ubuntu.com/ubuntu/pool/universe/liba/libav/libavresample-dev_9.18-0ubuntu0.14.04.1_amd64.deb
#   - sudo dpkg -i libavresample1_9.18-0ubuntu0.14.04.1_amd64.deb
#   - sudo dpkg -i libavresample-dev_9.18-0ubuntu0.14.04.1_amd64.deb
#   - wget http://ubuntu.secs.oakland.edu/pool/universe/f/ffmpeg/libswresample-ffmpeg1_2.7.2-1build1_amd64.deb
#   - wget http://ubuntu.secs.oakland.edu/pool/universe/f/ffmpeg/libswresample-dev_2.7.2-1build1_amd64.deb
#   - sudo dpkg -i libswresample-ffmpeg1_2.7.2-1build1_amd64.deb
#   - sudo dpkg -i libswresample-dev_2.7.2-1build1_amd64.deb

before_script:
#  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
  - sudo apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libavutil-dev
#https://launchpad.net/ubuntu/+source/ffmpeg

# before_script:
#   - wget https://gist.githubusercontent.com/xdamman/e4f713c8cd1a389a5917/raw/7ebe0b7010ad59a61ddccf5c455d226c843584dc/install_ffmpeg_ubuntu.sh
#   - source install_ffmpeg_ubuntu.sh

# before_script:
#   - wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
#   - tar xf ffmpeg-release-64bit-static.tar.xz

script: cargo build

after_script:
  - travis_wait cargo test --verbose --features build
