language: rust
sudo: false

rust:
  - nightly
#  - beta
#  - stable

addons:
  apt:
    packages:
      - nasm
      - libavutil-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavformat-dev
      - libavfilter-dev
      - libavresample-dev
      - libswresample-dev
      - libswscale-dev

script: cargo build

after_script:
  - travis_wait cargo test --verbose --features build
