language: rust
#sudo: false

rust:
  - nightly
#  - beta
#  - stable

addons:
  apt:
    packages:
      - nasm

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libavutil-dev libavformat-dev libavcodec-dev libswscale-dev

# before_script:
# #  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
#   - sudo apt-get update -qq
#   - sudo apt-get install -y libavcodec-dev libavformat-dev libswscale-dev libavutil-dev

script: cargo build

after_script:
  - travis_wait cargo test --verbose --features build
